# Generated by Django 5.0.1 on 2024-02-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pref_time',
            field=models.PositiveIntegerField(blank=True, default='test', null=True),
        ),
    ]
