# Generated by Django 5.0.1 on 2024-02-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
    ]
