# Generated by Django 5.0.1 on 2024-02-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_post_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commend',
            new_name='Comment',
        ),
    ]
